#!/bin/bash
# -*- mode: sh -*-
bundle exec \
       ruby \
       integration_spec/fake_pivotal_tracker.rb \
       -o 127.0.0.1 \
       -p 4567 &
export FAKE_PIVOTAL_TRACKER_PID=$!
rspec integration_spec/tracker_deliveries_integration_spec.rb

echo "Kill Fake PivotalTracker server on http://localhost:4567 [PID: ${FAKE_PIVOTAL_TRACKER_PID}]"
kill $FAKE_PIVOTAL_TRACKER_PID
